### PR TITLE
Cache BulkDataFile downloads in tmp dir.

### PR DESCRIPTION
**Pull request by msmorgan**
- Cache BulkDataFile downloads into OS temp folder.
- Add load_iter method for BulkDataFile.
- Implement bulk functions using load_iter.

Not sure about the last commit. Maybe having alternative functions
such as `oracle_cards_iter` would be preferable to changing the existing
ones.

### CODE REVIEW

**Comment by msmorgan** [comment]
Should this be behind a feature flag?

**Comment by mendess** [comment]
> Should this be behind a feature flag?

Yes, I think so

**Review by mendess — COMMENTED** [review]
Can you explain the array stream reader thing? I don't know if I understand.

**Comment by msmorgan** [comment]
> Can you explain the array stream reader thing? I don't know if I understand.

`serde_json` has a mode where it can read multiple objects one after another with no delimiter, as long as they're self-delimiting ([see `StreamDeserializer`](https://docs.rs/serde_json/1.0.64/serde_json/struct.StreamDeserializer.html)). The items are lazily parsed it's a lot less memory-intensive if the entire structure isn't stored to an array.

However, if there's an outer structure such as an array, the entire thing must be deserialized at the same time. So the ArrayStreamReader strips the outer array brackets `[]` and any commas separating elements, allowing `StreamDeserializer` to work. It assumes the input is roughly valid JSON, and as such treats nesting levels of `{}` to be equal to `{}`. It also handles strings and escapes.

It's possible there's another solution for this, such as writing a custom deserializer and visitor. I can look into it if you think this solution is too obtuse.

**Comment by mendess** [comment]
Alright, that makes sense. I don't think it's too obtuse it's basically a single method so it's fine.

**Review by mendess — APPROVED** [review]

**Pull request merged**
