### PR TITLE
Restrict module visibility and export useful types at root.

### PR DESCRIPTION
**Pull request by msmorgan**
- Delete unused colour.rs
- Remove an unnecessary unsafe block
- Add root exports for searchable objects.
- Restrict visibility of internal modules
- Remove redundant #[doc(inline)] attrs for exports out of private modules.
- Rename "colour" to "color" everywhere.

### CODE REVIEW

**Review by mendess — APPROVED** [review]
Ahh that colours module thing is quite embarrassing :sweat_smile:

**Comment by msmorgan** [comment]
Speaking of the colours module, do you think it makes sense (in another PR) to rename Colours and Colour structs to use the American English spelling, to match the spelling used by Scryfall and the module?

**Comment by mendess** [comment]
Yes, I think it's a good ideia, I've noticed that you found quite a few typos and inconsistencies already, thanks! You could do it in this PR no? Or am I missing something?

**Comment by msmorgan** [comment]
I just thought it was probably a separate PR conceptually. I'll add the commit to this one.

**Comment by msmorgan** [comment]
You should probably bump the minor version number after this change.

**Comment by mendess** [comment]
Yes, after all these PRs I'll bump to 0.8

**Comment by msmorgan** [comment]
Crate fully Americanized (U.S.A.! U.S.A.!). Ready to go.

**Pull request merged**
