### PR TITLE
Add rustfmt config and run nightly rustfmt.

### PR DESCRIPTION
**Pull request by msmorgan**
This is my preferred rustfmt config, but let me know if you want me to change anything. [Configs are documented here.](https://github.com/rust-lang/rustfmt/blob/master/Configurations.md)

I'll rebase to master and rerun rustfmt once the other PRs are merged.

### CODE REVIEW

**Comment by mendess** [comment]
Amazing. I agree with everything single option you have

**Review by mendess — APPROVED** [review]

**Comment by msmorgan** [comment]
Which of these two do you prefer? I added an alternative in the latest commit.

https://github.com/mendess/scryfall-rs/pull/14/commits/422fc410cb1c69ffe381e591d20b2ba3c5b43e28

**Comment by mendess** [comment]
I'm honestly kinda split. I usually manually do the Crate version but the module one also looks good. Pick what you like best

**Comment by msmorgan** [comment]
They're pretty close IMO too, but I think I prefer Module since it's a little easier to see at a glance. It's also closer to the style used by the standard library.

**Comment by msmorgan** [comment]
@mendess I've resolved all conflicts and cleaned up the commit history. This should be ready to merge.

**Pull request merged**
